spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8089

topic:
  inventory: Inventory-topic

eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8671/eureka/
